[application]
name = "Kilo"
id = "ports.antirez.kilo"

[entrypoints.main]
binary = "kilo"
input =  "terminal"
modes = ["terminal"]
default = "terminal"

[permissions]
filesystem = "mutable"
capabilities = [ "term-control" ]
